libra:
    batchDataSource:
        url: jdbc:postgresql://localhost:5432/jonnas
    stagingDB:
        url: jdbc:postgresql://localhost:5432/jonnas
        driverClassName:
        username: jonnas
        password: 123456
    dataDir: ${libra.homeDir}/data
    homeDir: /Users/zhongshuangli/source/mycode/projects/libra/libra_home
    jobBeansDir: ${libra.homeDir}/jobs
    jobBeansDir2: ${libra.homeDir}/jobs
    jobBeansDir3: ${libra.homeDir}/jobs
    reportDir: ${libra.homeDir}/reports
    scriptDir: ${libra.homeDir}/scripts
    # Enter an beforeJob, beforeStep, afterJob, afterStep event has been fired, let spring batch save the state before
    # fetching the state and send it to jobExecutionListeners
    updateThreadSleepBeforeUpdate: 300
    version: $project.version$
# Enables the interactive shell. If you use the web UI, keep this disabled
spring.shell.interactive.enabled: false

#vaadin.productionMode: true
vaadin.pnpm.enable: true

## Disable security for testing purposes
#spring:
#    autoconfigure:
#        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.security.user:
    name: admin
    password: 123456
    roles: ADMIN,BATCH_VIEW,BATCH_EXECUTE