libra:
    batchDataSource:
        url: jdbc:postgresql://localhost:5432/jonnas
    dataDir: ${libra.homeDir}/data
    homeDir: /Users/zhongshuangli/source/mycode/projects/libra/libra_home
    jobBeansDir: ${libra.homeDir}/jobs
    jobBeansDir2: ${libra.homeDir}/jobs
    jobBeansDir3: ${libra.homeDir}/jobs
    reportDir: ${libra.homeDir}/reports
    scriptDir: ${libra.homeDir}/scripts
spring:
    batch:
        initialize-schema: never
        job:
            enabled: false
    datasource:
        druid:
            initial-size: 5
            max-active: 20
            max-wait: 10
            min-idle: 5
            validationQuery: SELECT 1
        initialization-mode: never
        name: defaultDataSource
        password: 123456
        schema: classpath:sql/schema-postgresql.sql
        sql-script-encoding: UTF-8
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:postgresql://localhost:5432/jonnas
        username: jonnas
    quartz:
        auto-startup: true
        jdbc:
            initialize-schema: never
        job-store-type: jdbc
        overwrite-existing-jobs: true
        properties:
            org:
                quartz:
                    jobStore:
                        class: org.quartz.impl.jdbcjobstore.JobStoreTX
                        clusterCheckinInterval: 50000
                        dataSource: quartz
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
                        isClustered: true
                        tablePrefix: qrtz_
                        useProperties: false
                    scheduler:
                        instanceId: auto
                        instanceName: clusteredScheduler
                    threadPool:
                        class: org.quartz.simpl.SimpleThreadPool
                        threadCount: 10
                        threadPriority: 5
                        threadsInheritContextClassLoaderOfInitializingThread: true
vaadin:
    pnpm:
        enable: true
