# Default properties
vaadin:
  urlMapping: /ui/*
  heartbeatInterval: 30
  closeIdleConnections: true

server.servlet.session.timeout: 300

libra:
#  version: '@project.version@'
  buildTime: '@librabuildtimestamp@'
  build: 0
#  # Efter an beforeJob, beforeStep, afterJob, afterStep event has been fired, let spring batch save the state before
#  # fetching the state and send it to jobExecutionListeners
#  updateThreadSleepBeforeUpdate: 300
  # Additional job bean directories
  jobBeansDir2: replaceme
  jobBeansDir3: replaceme
  jobRepository.isolationLevelForCreate: ISOLATION_READ_COMMITTED

spring:
  batch:
    initialize-schema: never
    job.enabled: false
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 10
      min-idle: 5
      validationQuery: SELECT 1
    initialization-mode: never
    name: defaultDataSource
    password: 123456
    schema: classpath:sql/schema-postgresql.sql
    sql-script-encoding: UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://localhost:5432/jonnas
    username: jonnas
  quartz:
    auto-startup: true
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            clusterCheckinInterval: 50000
            dataSource: quartz
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            tablePrefix: qrtz_
            useProperties: false
          scheduler:
            instanceId: auto
            instanceName: clusteredScheduler
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true